const data={
    products:[
        {
          _id:'1',
          name:'Nike slim T-Shirt',
          category:'T-Shirts',
          Image:'/images/product1.jpg.webp' ,
          price:120 ,
          brand:'Nike' ,
          rating:4.5 ,
          numReviews:10,
          description:'high quality product',
        },
        {
            _id:'2',
            name:'Addidas Fit T-Shirt',
            category:'T-Shirts',
            Image:'/images/product2.jpg' ,
            price:100 ,
            brand:'Addidas' ,
            rating:4.0 ,
            numReviews:10,
            description:'high quality product',
          },
          {
            _id:'3',
            name:'Lacoste slim T-Shirt',
            category:'T-Shirts',
            Image:'/images/product3.jpg' ,
            price:220 ,
            brand:'Nike' ,
            rating:4.8 ,
            numReviews:17,
            description:'high quality product',
          },
          {
            _id:'4',
            name:'Nike slim Pants',
            category:'Pants',
            Image:'/images/product4.webp' ,
            price:78 ,
            brand:'Nike' ,
            rating:4.5 ,
            numReviews:14,
            description:'high quality product',
          },
          {
            _id:'5',
            name:'Puma slim Pants',
            category:'Pants',
            Image:'/images/product5.webp' ,
            price:65 ,
            brand:'puma' ,
            rating:4.2 ,
            numReviews:10,
            description:'high quality product',
          },
          {
            _id:'6',
            name:'Puma fit Pants', 
            category:'Pants',
            Image:'/images/product6.webp' ,
            price:139 ,
            brand:'Puma' , 
            rating:4.5 ,
            numReviews:15,
            description:'high quality product',
          },
    ],
};
export default data;